# Generated by Django 5.1.6 on 2025-04-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suzaku', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipoparticipante',
            name='derrotas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='equipoparticipante',
            name='puntos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='equipoparticipante',
            name='victorias',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
