# Generated by Django 5.1.6 on 2025-03-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suzaku', '0002_postequipo_remove_usuario_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('primer_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('nickname', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='equipo_integrantes/')),
                ('tipo', models.CharField(choices=[('jugador', 'Jugador'), ('creador', 'Creador de Contenido')], default='creador', max_length=20)),
            ],
        ),
    ]
