# Generated by Django 5.1.6 on 2025-04-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suzaku', '0002_alter_equipoparticipante_derrotas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipoparticipante',
            name='empates',
            field=models.IntegerField(default=0),
        ),
    ]
