# Generated by Django 5.1.6 on 2025-04-24 21:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suzaku', '0004_sponsor_sponsorimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='portada',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='sponsors/'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorimage',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorimage',
            name='imagen',
            field=models.ImageField(upload_to='sponsors/imagenes/'),
        ),
    ]
