# Generated by Django 5.1.6 on 2025-05-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suzaku', '0005_remove_sponsor_portada_sponsor_creado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
