# Generated by Django 5.1.6 on 2025-05-21 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suzaku', '0007_categoriaproducto_color_productotipo_talla_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
    ]
