# Generated by Django 5.1.6 on 2025-06-05 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suzaku', '0008_alter_stock_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('producto', 'talla', 'color')},
        ),
    ]
