# Generated by Django 5.1.6 on 2025-06-05 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suzaku', '0009_alter_stock_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoimagen',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes_color', to='suzaku.color'),
        ),
    ]
