# Generated by Django 5.1.6 on 2025-06-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suzaku', '0010_productoimagen_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_miniatura',
            field=models.ImageField(blank=True, null=True, upload_to='productos/miniaturas/'),
        ),
    ]
