# Generated by Django 5.1.6 on 2025-06-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suzaku', '0011_producto_imagen_miniatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='valoraciones/'),
        ),
    ]
