# Generated by Django 5.1.6 on 2025-06-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suzaku', '0012_valoracion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracion',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
