# Generated by Django 5.1.6 on 2025-06-08 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suzaku', '0013_valoracion_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='productopedido',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suzaku.color'),
        ),
        migrations.AddField(
            model_name='productopedido',
            name='talla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suzaku.talla'),
        ),
    ]
