# Generated by Django 5.1.6 on 2025-06-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suzaku', '0014_productopedido_color_productopedido_talla'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='usuarios/default-user.png', null=True, upload_to='usuarios/'),
        ),
    ]
