# Generated by Django 5.1.6 on 2025-06-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suzaku', '0015_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='personalizacion',
            field=models.BooleanField(default=False, help_text='¿Permite personalización con nombre?'),
        ),
    ]
