# Generated by Django 5.1.6 on 2025-06-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suzaku', '0016_producto_personalizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='productopedido',
            name='nombre_personalizado',
            field=models.CharField(blank=True, help_text='Nombre personalizado si el producto lo permite', max_length=100, null=True),
        ),
    ]
